### ISSUE TITLE
Ecto 2.0

### ISSUE THREAD

**Issue by veverkap** [TheRealReal/new-relixir#1]
Do you have any plans for supporting Ecto 2.0?

**Comment by fbjork** [comment]
@veverkap Absolutely. Once 2.0.0 final is released we will work on support for it.

**Comment by veverkap** [comment]
Started #2

**Comment by linjunpop** [comment]
Echo does released 2.0.1 (https://hex.pm/packages/ecto)

**Comment by veverkap** [comment]
@fbjork #2 looks good for now with help from @romul

**Comment by zapient** [comment]
This would be nice to have now

**Comment by mathieujobin** [comment]
#6 got merged, why not closing this?
