### ISSUE TITLE
Question: Non-Phoenix plug support

### ISSUE THREAD

**Issue by alanpeabody** [TheRealReal/new-relixir#11]
Do you have any interest in supporting non-phoenix applications in this lib?

I like the plugs and the transaction stuff you have going, but it would be great to leverage it without the phoenix dependency (eg making it optional).

Happy to open a branch exploring that if that aligns with the library direction.

**Comment by dcuddeback** [comment]
@alanpeabody Yes, absolutely. Not just interested, but it's part of our long-term vision for this project to support plain Plug projects. It may be a while before we work on it ourselves, but we'd be happy to look at a PR if you tackle it before we get to it. :)

**Comment by alanpeabody** [comment]
@dcuddeback Cool, I also don't know when I might get to it, but it is on my todo list.

**Comment by britto** [comment]
Hi, @alanpeabody. I've been working on this in #31. It would be great if you could test it out and give us some feedback.

**Comment by coburncoburn** [comment]
Everything should work fine in a plug app using https://github.com/TheRealReal/new-relixir/blob/master/lib/new_relixir/instrumenters/plug.ex#L3
