### ISSUE TITLE
Use Phoenix instrumentation?

### ISSUE THREAD

**Issue by mtarnovan** [TheRealReal/new-relixir#12]
Phoenix has [built-in instrumentation](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L230) 

Wouldn't it be more natural to hook into this instead of wrapping the `Repo` and passing `conn` around? Somehow this rubs me the wrong way, it's a boundary violation.

**Comment by mikekelly** [comment]
Also wondering about this :)

**Comment by alanpeabody** [comment]
I have been looking into this a bit, it seems pretty feasible and with some minor changes to phoenix we could get an additional "render" reported in the breakdown.

However I think it is a pretty significant re-org/api chage (although most code still applies). It would be nice to support raw plug as well as phoenix instrumentation.

@dcuddeback how open to API and architectural changes are you if I can come up with something halfway decent?

**Comment by mathieujobin** [comment]
5 months later... 

did anyone start drafting out those changes in a fork ? 

I would sure prefer to put the plug in my pipeline and not having to pass the `conn: conn` around

I also don't understand why Ecto is always required to instrument an HTTP hit on newrelic ?!?
I opened #18 for this, and if I understand #16 correctly he is having the same question.

**Comment by alanpeabody** [comment]
@mathieujobin This has a different set of drawbacks, but you can check it out: https://github.com/ello/newrelic_phoenix

**Comment by britto** [comment]
Hi, @mtarnovan. I've been working on this in #31. It would be great if you could test it out and give us some feedback.

**Comment by fbjork** [comment]
This is now merged to master
