### ISSUE TITLE
Is there a way to use the ecto support without the Plug.Repo? I want to use them in a separate umbrella project

### ISSUE THREAD

**Issue by mrkaspa** [TheRealReal/new-relixir#16]

**Comment by kwokster10** [comment]
👍 . Is this a repeat of https://github.com/TheRealReal/new-relixir/issues/11?

**Comment by coburncoburn** [comment]
if you call CurrentTransaction.set("my parent transaction") before using the calling MyApp.Repo.NewRelic.all(User), your repo transactions should be grouped appropriately. It does not actually rely on Plug specifically. Please reopen the issue with more explanation if this does not work.
