### ISSUE TITLE
no reporting after following instructions

### ISSUE THREAD

**Issue by mathieujobin** [TheRealReal/new-relixir#17]
Sorry if this isn't the right place to ask for help

I'm trying to setup this into my new app. my app is very small, only has couple of pages.

I followed the steps described in the readme, I'm not seeing any errors. but it does not report anything onto newrelic. 

by the way, when the app compiles, I see this warning being displayed roughly 30 times
```
warning: variable "repo" does not exist and is being expanded to "repo()", please use parentheses to remove the ambiguity or change the variable name
  lib/web/repo.ex:5
```

line 5 being `use NewRelixir.Plug.Repo, repo: Web.Repo`

**Comment by mathieujobin** [comment]
looks like this is duplicate of #7 

will reopen if it still does not work

**Comment by ju-Skinner** [comment]
@mathieujobin How did you resolve the warnings? Looking at the referenced PR, it didn't appear to resolve the warnings. If you could share, that would be helpful and appreciated.
