### ISSUE TITLE
Why are they 2 config entries

### ISSUE THREAD

**Issue by illiatdesdindes** [TheRealReal/new-relixir#40]
Hello there :) !

Was wondering if it was intentional that those 2 lines use `Application.get_env(:new_relic, :some_key)` instead of `Application.get_env(:new_relixir, :some_key)` ?

https://github.com/TheRealReal/new-relixir/blob/v0.4.1/lib/new_relixir/agent.ex#L50
https://github.com/TheRealReal/new-relixir/blob/v0.4.1/lib/new_relixir/polling.ex#L5

**Comment by coburncoburn** [comment]
you are correct, those are in error, would you like to open a PR that uses :new_relixir instead?

**Comment by coburncoburn** [comment]
fixed in https://github.com/TheRealReal/new-relixir/pull/43
