### ISSUE TITLE
How can I use NewRelixir.Plug.Repo out of the scope of Phoenix Controller

### ISSUE THREAD

**Issue by MrCoffey** [TheRealReal/new-relixir#61]
Hi there, the actual documentation says: 

> These database calls must be done in the scope of an instrumented Phoenix controller or Plug endpoint. Calls made from spawned child subprocesses are supported.

I would like to be able to use the functionality of this module inside an umbrella application, that doesn't implement a server.

Thank you in advance.

**Comment by coburncoburn** [comment]
@MrCoffey Somewhere along the way ( before making any calls that should be measured ) you must set the current transaction such as https://github.com/TheRealReal/new-relixir/blob/master/lib/new_relixir/instrumenters/plug.ex#L44
or
https://github.com/TheRealReal/new-relixir/blob/master/lib/new_relixir/instrumenters/phoenix.ex#L27.

Maybe at the start of whatever chain of functions in the application will ultimately be hitting the database?

**Comment by MrCoffey** [comment]
Thank you so much!
