### ISSUE TITLE
Getting  (ArgumentError) argument error

### ISSUE THREAD

**Issue by ashneyderman-tcb** [TheRealReal/new-relixir#62]
I am seeing exception thrown:

`
[error] Task #PID<0.695.0> started from #PID<0.693.0> terminating
** (ArgumentError) argument error
    :erlang.process_info(APIRequestStorage.Plug.TaskSupervisor, :dictionary)
    (elixir) lib/process.ex:646: Process.info/2
    (new_relixir) lib/new_relixir/current_transaction.ex:49: NewRelixir.CurrentTransaction.extract_transaction/1
    (elixir) lib/enum.ex:2914: Enum.find_value_list/3
    (new_relixir) lib/new_relixir/current_transaction.ex:44: NewRelixir.CurrentTransaction.search_on_ancestors/0
    (new_relixir) lib/new_relixir/current_transaction.ex:21: NewRelixir.CurrentTransaction.get/0
    (new_relixir) lib/new_relixir/plug/instrumentation.ex:69: NewRelixir.Plug.Instrumentation.record/2
    (new_relixir) lib/new_relixir/plug/instrumentation.ex:28: NewRelixir.Plug.Instrumentation.instrument_db/4
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.3580135/0 in APIRequestStorage.Plug.store_api_request/2>
    Args: []
`
It might be that my erlang version is newer (20.1) than what the code can handle. the 

lib/new_relixir/current_transaction.ex:49: Process.info(pid, :dictionary)

that line expects a real pid not an alias (registered name) - i.e. not APIRequestStorage.Plug.TaskSupervisor

**Comment by coburncoburn** [comment]
This was actually fixed in the latest version, see this commit https://github.com/TheRealReal/new-relixir/pull/58/files#diff-a6366d0c762a4a27da2e01a08c37cdf8R60. 

Try updating to 0.4.7.

**Comment by ashneyderman-tcb** [comment]
yes, thank you. I did figure it out. Jus forgot to close the issue.
