### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by romul** [TheRealReal/new-relixir#7]
I'm trying to use new-relixir with a project on Elixir 1.3.1 
Everything is configured and looks ok, but no data appear in NewRelic. 
Where could I look to fix the problem?

Besides the app, I used a simple test

``` elixir
iex(1)> t = NewRelixir.Transaction.start("Test")
%NewRelixir.Transaction{name: "Test", start_time: {1468, 315927, 779567}}
iex(2)> NewRelixir.Transaction.finish(t)    
:ok
```

No error, but no data in NR as well.
Maybe some configuration on NewRelic side should be done?

**Comment by dcuddeback** [comment]
New Relic is really picky about the data we send it. `"Test"` is treated by New Relic as a URL path, so it needs to begin with a slash. Try `"/Test"`.

**Comment by romul** [comment]
@dcuddeback Nope, isn't working either.
How could I find out: is data sent to NR or not?
And should it be a separate app on NR-side or could I send data to existing NR-app (based on RoR-project)?

**Comment by romul** [comment]
@dcuddeback I've found the reason. `jiffy` could not compiled properly with Elixir 1.3.1, b/c it expects rebar2. More info: https://github.com/erlang/rebar3/issues/1181 and https://github.com/davisp/jiffy/pull/118

**Solution**
Add `jiffy` explicitly to mix.exs this way:

``` elxir
  {:jiffy, github: "davisp/jiffy", branch: "feature-add-rebar3-support", override: true}
```

**Comment by mathieujobin** [comment]
in my fork I am simply switching back to upstream newrelic-erlang
which does not have jiffy locked down
https://github.com/mathieujobin/new-relixir/commit/3231a27b3a7dc6cc6163a10552825d7c0244a80e

it works !!!
