### ISSUE TITLE
0.5.0: NewRelixir.Polling: push failed: %UndefinedFunctionError{arity: 1, function: :decode!, message: nil, module: Poison, reason: nil}

### ISSUE THREAD

**Issue by tobiasmcnulty** [TheRealReal/new-relixir#83]
After noticing the recent (unreleased) version 0.5.0 which includes support for Ecto 3, I thought I'd give it a try.

I updated my deps to point to git, like so:

      {:phoenix, "~> 1.4.0"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.0"},
      # ...
      {:new_relixir, git: "https://github.com/TheRealReal/new-relixir.git"}

This successfully got past the deps errors when trying to install newrelixer 0.4.0.

However, when running my application, I see this from time to time in the console:

    11:40:04.929 [info] New Relixir set up for 'phxhello_newrelixir'.
    ...
    11:40:35.161 [error] NewRelixir.Polling: push failed: %UndefinedFunctionError{arity: 1, function: :decode!, message: nil, module: Poison, reason: nil}

And the application name never shows up in New Relic. Perhaps this is already planned to be fixed in 0.5.0 but thought I'd post this just in case. I installed/configured newrelixir per the current README.

**Comment by zapient** [comment]
@tobiasmcnulty thanks for the heads up. Yes this will be addressed before the official 0.5.0 release.

**Comment by alexgaribay** [comment]
Poison just needs to be added as an explicit dependency since Phoenix 1.4 and Ecto 3.0 do not use it as a dependency. Maybe this would be a good time to switch the library to use Jason instead of Poison as well.
